[project]
name = "banking-system-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "email-validator>=2.2.0",
    "plotly>=6.0.1",
    "streamlit>=1.44.1",
]
